<?php

/**
 * Module for implementing a dynamic video widget using AngularJS
 *
 * @author Yevgeny Ananin <yananin@summitmediagroup.com>
 */

/**
 * Implements hook_theme
 */
function video_widget_theme($existing, $type, $theme, $path) {
  return array(
    'video_widget' => array(
      'template' => 'video_widget_includes/templates/video-widget',
      'variables' => array('nid' => NULL),
    ),
  );
}

/*
 * Implements hook_menu
 */
function video_widget_menu() {
  // #46 Build out a menu router path that can supply templates to angular,
  // since angular loads files through ajax and they can't be referenced with
  // a relative path
  $items['video-widget/resource/%/%'] = array(
    'page callback' => 'video_widget_resource',
    'page arguments' => array(2,3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'video_widget_includes/video-widget.inc'
  );

  return $items;
}

/*
 * Implements hook_page_alter
 */
function video_widget_page_alter(&$page) {

  // Add the files for our Angular app
  drupal_add_js(drupal_get_path('module','video_widget').'/video_widget_includes/angular/app.js');
  //drupal_add_js('http://summitmediagroup.magnify.net/embed/player/lightbox.js', array('type' => 'external', 'group' => JS_LIBRARY, 'weight' => -100));
  drupal_add_js(drupal_get_path('module', 'video_widget').'/video_widget_includes/js/lightbox.js');
  drupal_add_css(drupal_get_path('module','video_widget').'/video_widget_includes/css/video_widget.css');
  /*
  $stuff = array(
    'stuff' => array(
      '#markup' => theme('video_widget', array('nid' => '1000')),
      '#weight' => 0,
    ),
    'stuff2' => array(
      '#markup' => theme('video_widget', array('nid' => '2000')),
      '#weight' => 0,
    ),
    'stuff3' => array(
      '#markup' => theme('video_widget', array('nid' => '3000')),
      '#weight' => 0,
    ),
  );
  array_unshift($page['content'], $stuff);*/
}

/*
 * Implements hook_smg_angular_add_template
 */
function video_widget_smg_angular_add_template() {
  $templates = array(
    'video' => '/' . drupal_get_path('module','video_widget') . '/video_widget_includes/angular/templates/video.html',
  );

  return $templates;
}
